import { Montserrat } from "next/font/google";
import "./globals.css";
import "../styles/global.scss";

import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserat = Montserrat({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserat.className}>
      <body>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
