import { Raleway } from "next/font/google";
import "./globals.css";
import "../styles/global.scss";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={raleway.className}>
      <body>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
